diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor=nano.exe
pull.rebase=false
credential.helper=manager
user.email=ratchaya166@gmail.
user.name=ratchaya
core.longpaths=true
alias.st=status
alias.ci=commit
alias.br=branch
alias.co=checkout
alias.p=push origin
alias.cap=!f() { git commit -m "$@"; }; f
alias.int=!f() { git cap "🎉 initial commit $1 $2"; }; f
alias.rocket=!f() { git cap "🚀 implementing a new feature $1 $2"; }; f
alias.con=!f() { git cap "🚧  work in progress $1 $2"; }; f
alias.conf=!f() { git cap "🔧 Add or update configuration files.  $1 $2"; }; f
alias.new=!f() { git cap " ⚗  Experiment new things$ 1 $2"; }; f
alias.speark=!f() { git cap " ✨  Introduce new features $1 $2"; }; f
alias.art=!f() { git cap " 🎨   format of the code $1 $2"; }; f
alias.ref=!f() { git cap " ♻️  refactory code $1 $2"; }; f
alias.move=!f() { git cap " 🚚  move file $1 $2"; }; f
alias.break=!f() { git cap " 💥  braking changes $1 $2"; }; f
alias.fire=!f() { git cap " 🔥  remove file $1 $2"; }; f
alias.cri=!f() { git cap " 🚑 critical hotfix $1 $2"; }; f
alias.fix=!f() { git cap " 🔨   fixing a bug or issue $1 $2"; }; f
alias.asset=!f() { git cap " 🍱   add or update assets $1 $2"; }; f
alias.database=!f() { git cap " 🗃  database changes $1 $2"; }; f
alias.rmlog=!f() { git cap " 🔇  remove log $1 $2"; }; f
alias.seeder=!f() { git cap " 🌱  update or changes seeder daabase $1 $2"; }; f
alias.compile=!f() { git cap " 📦  Add or update compiled files or packages $1 $2"; }; f
alias.comment=!f() { git cap " 💡💬 add good comment $1 $2"; }; f
alias.doc=!f() { git cap " 📝 write docs $1 $2"; }; f
alias.pin=!f() { git cap " 📌🏷️ specific version $1 $2"; }; f
alias.bookmark=!f() { git cap " 🔖   version tags $1 $2"; }; f
alias.test=!f() { git cap " ✅ Add or update tests. $1 $2"; }; f
alias.conf=!f() { git cap " 🔧 Add or update configuration files $1 $2"; }; f
alias.lib=!f() { git cap " 💄 Add or update the UI and style files $1 $2"; }; f
alias.typo=!f() { git cap " ✏️ Fix typos $1 $2"; }; f
alias.acc=!f() { git cap " ♿️ Improve accessibility $1 $2"; }; f
alias.mock=!f() { git cap " 🤡 Mock things $1 $2"; }; f
alias.seo=!f() { git cap " 🔍 Improve SEO $1 $2"; }; f
alias.adddepen=!f() { git cap " ➕ Add a dependency $1 $2"; }; f
alias.minusdepen=!f() { git cap " ➖ Remove a dependency $1 $2"; }; f
alias.ci=!f() { git cap " 👷 Add or update CI build system. $1 $2"; }; f
core.bare=false
core.repositoryformatversion=0
core.filemode=false
core.symlinks=false
core.ignorecase=true
core.logallrefupdates=true
remote.origin.url=https://github.com/ratchaya166/mobileApp.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
